/**
 * Created by Administrator on 2017/5/2 0002.
 */
export const CHANGE_ROUTE='CHANGE_ROUTE';
export const CHANGE_TIMELINE_MSG='CHANGE_TIMELINE_MSG';
export const CHANGE_DETAIL_MSG='CHANGE_DETAIL_MSG';
export const SET_TIMELINE_LEFT='SET_TIMELINE_LEFT';
export const BACK_TO_LINE='BACK_TO_LINE';
export const BACK_TO_LINE_BTN_DOWN='BACK_TO_LINE_BTN_DOWN';
export const BACK_TO_LINE_BTN_UP='BACK_TO_LINE_BTN_UP';
export const DETAILPAGE_IN='DETAILPAGE_IN';
export const DETAILPAGE_OUT='DETAILPAGE_OUT';
export const PREV='PREV';
export const NEXT='NEXT';
export const TAB_IN_TIMELINE='TAB_IN_TIMELINE';
export const TAB_IN_DETAIL='TAB_IN_DETAIL';
export const RESET_ITEMLINE='RESET_ITEMLINE';
export const LOADING_SHOW='LOADING_SHOW';
export const LOADING_HIDE='LOADING_HIDE';
export const STORE_TIMELINEALL='STORE_TIMELINEALL';
export const CHANGE_BTN_COLOR='CHANGE_BTN_COLOR';
export const CIRCLE_UP='CIRCLE_UP';
export const CIRCLE_DOWN='CIRCLE_DOWN';
export const CIRCLE_COLOR='CIRCLE_COLOR';
export const RESOURCE_SHOW='RESOURCE_SHOW';
export const RESOURCE_HIDE='RESOURCE_HIDE';
export const CHANGE_BOOK_PAGE='CHANGE_BOOK_PAGE';
export const CHANGE_BOOK_TOTAL='CHANGE_BOOK_TOTAL';
export const CHANGE_MOVIE_PAGE='CHANGE_MOVIE_PAGE';
export const CHANGE_MOVIE_TOTAL='CHANGE_MOVIE_TOTAL';
export const CHANGE_RESOURCE_ROUTE='CHANGE_RESOURCE_ROUTE';
export const CHANGE_BOOK_SEARCH='CHANGE_BOOK_SEARCH';
export const CHANGE_MOVIE_SEARCH='CHANGE_MOVIE_SEARCH';

